/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Codigo;

/**
 *
 * @author fecq8
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    double operando1 = 0;  //primer operando
    String operacion = "";
    /**
     * Creates new form VentanaCalculadora
     */
    public VentanaCalculadora() {
        initComponents();
    }
    private void numeroPulsado(String numero){
        if (pantalla.getText() == "0"){
           pantalla.setText(numero);
        }else{
        pantalla.setText(pantalla.getText() + numero);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        jButton07 = new javax.swing.JButton();
        jButton08 = new javax.swing.JButton();
        jButton09 = new javax.swing.JButton();
        jButtonMas = new javax.swing.JButton();
        jButton04 = new javax.swing.JButton();
        jButton05 = new javax.swing.JButton();
        jButton06 = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jButton01 = new javax.swing.JButton();
        jButton02 = new javax.swing.JButton();
        jButton03 = new javax.swing.JButton();
        jButtonPor = new javax.swing.JButton();
        jButton00 = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonDividir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setBackground(new java.awt.Color(0, 0, 0));
        pantalla.setFont(new java.awt.Font("Perpetua Titling MT", 0, 48)); // NOI18N
        pantalla.setForeground(new java.awt.Color(255, 0, 0));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");
        pantalla.setOpaque(true);

        jButton07.setBackground(new java.awt.Color(0, 255, 255));
        jButton07.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton07.setForeground(new java.awt.Color(255, 102, 0));
        jButton07.setText("7");
        jButton07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton07MousePressed(evt);
            }
        });

        jButton08.setBackground(new java.awt.Color(0, 255, 255));
        jButton08.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton08.setForeground(new java.awt.Color(255, 102, 0));
        jButton08.setText("8");
        jButton08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton08MousePressed(evt);
            }
        });

        jButton09.setBackground(new java.awt.Color(0, 255, 255));
        jButton09.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton09.setForeground(new java.awt.Color(255, 102, 0));
        jButton09.setText("9");
        jButton09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton09MousePressed(evt);
            }
        });

        jButtonMas.setBackground(new java.awt.Color(0, 255, 255));
        jButtonMas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButtonMas.setForeground(new java.awt.Color(255, 102, 0));
        jButtonMas.setText("+");
        jButtonMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMasMousePressed(evt);
            }
        });

        jButton04.setBackground(new java.awt.Color(0, 255, 255));
        jButton04.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton04.setForeground(new java.awt.Color(255, 102, 0));
        jButton04.setText("4");
        jButton04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton04MousePressed(evt);
            }
        });

        jButton05.setBackground(new java.awt.Color(0, 255, 255));
        jButton05.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton05.setForeground(new java.awt.Color(255, 102, 0));
        jButton05.setText("5");
        jButton05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton05MousePressed(evt);
            }
        });

        jButton06.setBackground(new java.awt.Color(0, 255, 255));
        jButton06.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton06.setForeground(new java.awt.Color(255, 102, 0));
        jButton06.setText("6");
        jButton06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton06MousePressed(evt);
            }
        });

        jButtonMenos.setBackground(new java.awt.Color(0, 255, 255));
        jButtonMenos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButtonMenos.setForeground(new java.awt.Color(255, 102, 0));
        jButtonMenos.setText("-");
        jButtonMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMenosMousePressed(evt);
            }
        });

        jButton01.setBackground(new java.awt.Color(0, 255, 255));
        jButton01.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton01.setForeground(new java.awt.Color(255, 102, 0));
        jButton01.setText("1");
        jButton01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton01MousePressed(evt);
            }
        });

        jButton02.setBackground(new java.awt.Color(0, 255, 255));
        jButton02.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton02.setForeground(new java.awt.Color(255, 102, 0));
        jButton02.setText("2");
        jButton02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton02MousePressed(evt);
            }
        });

        jButton03.setBackground(new java.awt.Color(0, 255, 255));
        jButton03.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton03.setForeground(new java.awt.Color(255, 102, 0));
        jButton03.setText("3");
        jButton03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton03MousePressed(evt);
            }
        });

        jButtonPor.setBackground(new java.awt.Color(0, 255, 255));
        jButtonPor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButtonPor.setForeground(new java.awt.Color(255, 102, 0));
        jButtonPor.setText("*");
        jButtonPor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonPorMousePressed(evt);
            }
        });

        jButton00.setBackground(new java.awt.Color(0, 255, 255));
        jButton00.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton00.setForeground(new java.awt.Color(255, 102, 0));
        jButton00.setText("0");
        jButton00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton00MousePressed(evt);
            }
        });

        jButtonIgual.setBackground(new java.awt.Color(0, 255, 255));
        jButtonIgual.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButtonIgual.setForeground(new java.awt.Color(255, 102, 0));
        jButtonIgual.setText("=");
        jButtonIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonIgualMousePressed(evt);
            }
        });

        jButtonDividir.setBackground(new java.awt.Color(0, 255, 255));
        jButtonDividir.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButtonDividir.setForeground(new java.awt.Color(255, 102, 0));
        jButtonDividir.setText("/");
        jButtonDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonDividirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton07, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton08, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton05, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton06, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton07, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton08, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton06, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton05, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton00, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton07MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton07MousePressed
       numeroPulsado("7");
    }//GEN-LAST:event_jButton07MousePressed

    private void jButton09MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton09MousePressed
        numeroPulsado("9");
    }//GEN-LAST:event_jButton09MousePressed

    private void jButtonMasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMousePressed
        
    }//GEN-LAST:event_jButtonMasMousePressed

    private void jButton08MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton08MousePressed
        numeroPulsado("8");
    }//GEN-LAST:event_jButton08MousePressed

    private void jButton04MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton04MousePressed
        numeroPulsado("4");
    }//GEN-LAST:event_jButton04MousePressed

    private void jButton06MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton06MousePressed
       numeroPulsado("6");
    }//GEN-LAST:event_jButton06MousePressed

    private void jButtonMenosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosMousePressed

    private void jButton05MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton05MousePressed
        numeroPulsado("5");
    }//GEN-LAST:event_jButton05MousePressed

    private void jButton01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton01MousePressed
       numeroPulsado("1");
    }//GEN-LAST:event_jButton01MousePressed

    private void jButton03MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton03MousePressed
        numeroPulsado("3");
    }//GEN-LAST:event_jButton03MousePressed

    private void jButtonPorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPorMousePressed

    private void jButton02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton02MousePressed
        numeroPulsado("2");
    }//GEN-LAST:event_jButton02MousePressed

    private void jButtonIgualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIgualMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIgualMousePressed

    private void jButtonDividirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDividirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDividirMousePressed

    private void jButton00MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton00MousePressed
       numeroPulsado("0");
    }//GEN-LAST:event_jButton00MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton00;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton03;
    private javax.swing.JButton jButton04;
    private javax.swing.JButton jButton05;
    private javax.swing.JButton jButton06;
    private javax.swing.JButton jButton07;
    private javax.swing.JButton jButton08;
    private javax.swing.JButton jButton09;
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonPor;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
